### ISSUE TITLE
Readme Improvement

### ISSUE THREAD

**Issue by meets2tarun** [fossasia/Ember_Simple_Calculator#6]
Although the readme is well-maintained but it needs to improvement. As one will not search under the /calculator/ for the deployment option, so on the front there should be an option which link to rest of the options.
We can look good readme as: https://github.com/fossasia/open-event-webapp/blob/development/README.md

**Comment by 0x48piraj** [comment]
> Latest commit in `repo` you just referenced, is mine :wink: 
Anyways, You're right, all are **ember.js** apps, and so, deployment process will be the same :+1: 
Can I claim this @meets2tarun ?
